services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - chroma  
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./chroma_db:/data
    ports:
      - "8765:8000"
